name: ckvf
description: Cryptographic Key Vault Format (CKVF) Dart SDK — SComm.AI Draft 0.1.
version: 0.1.1
homepage: https://github.com/scomm-public/ckvf/tree/main/packages/dart
repository: https://github.com/scomm-public/ckvf
issue_tracker: https://github.com/scomm-public/ckvf/issues
documentation: https://github.com/scomm-public/ckvf/tree/main/specification
topics:
  - crypto
  - vault
  - openpgp
  - smime

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  unorm_dart: ^0.3.0

dev_dependencies:
  crypto: ^3.0.6
  cryptography: ^2.7.0
  lints: ^6.0.0
  test: ^1.25.0
